### ISSUE TITLE
Make a class to send email

### ISSUE THREAD

**Issue by KevinEtienne** [incuna/incuna-mail#17]
It would be great to have one or more `EmailMessage` classes which would allow to customise the message settings (e.g.: defining an html message based on user preference, changing the sender...).

One way to do it would be to have a base class which would define a common behavior to create and send a message, and to be consistent `incuna_mail` would have two other classes for sending plain text message and html messages from templates.

This would have three advantages:
 - not forcing the user to send email from templates;
 - adding hooks to override any arguments before sending an email;
 - using a class to define how other system can send emails (example: one can decide the email class which can be defined in a setting or in a base class).

**Comment by Ian-Foote** [comment]
What does this gain us that django's built in [`EmailMessage`](https://docs.djangoproject.com/en/1.7/topics/email/#the-emailmessage-class) class doesn't have?

**Comment by KevinEtienne** [comment]
Good point, looks like the advantage of the `send` method in `incuna_mail` is to allow defining a text and a html message, and simplifies [making list](https://github.com/incuna/incuna-mail/blob/89769952d975c469592dda893f4ced4952f93cf7/incuna_mail.py#L25) from `to`, `cc` and `bcc`.

Looks like the `__init__` method from `EmailMessage` and `EmailMultiAlternative` could be reused. A new class could take advantage of this and could override `send` to choose wherever to send an `EmailMessage` or a `EmailMultiAlternative` based on our current custom arguments `template_name` and `html_template_name`.

**Comment by meshy** [comment]
I think this stems from a desire to ease the sending of notifications to users upon certain events in one of our private projects. Am I correct, @KevinEtienne?

As I understand it, that particular requirement may also benefit from the consideration of alternate methods of notification such as SMS, and as such, does not really belong here.

Furthermore, unless there is a very compelling case for it, I would really like to keep this project as simple as possible. It currently has a very clean API, and simple remit, and it would seem a shame to start polluting that for something of questionable use.

**Comment by KevinEtienne** [comment]
Thanks @meshy looks like I was trying to force `incuna_mail` to have another API which sounds more like another third party library.

**Comment by meshy** [comment]
:+1: Thanks @KevinEtienne
